
import { AppLanguage } from './types';

export const UI_STRINGS: Record<AppLanguage, any> = {
  ja: {
    title: 'Koe-Master',
    subtitle: 'AI日本語発音コーチ',
    mode_text: 'テキスト練習',
    mode_free: '自由発話',
    level_beginner: '初級',
    level_intermediate: '中級',
    level_advanced: '上級',
    placeholder_text: '練習したい日本語を入力してください...',
    start_recording: '録音開始',
    stop_recording: '録音停止',
    upload_file: '音声ファイルをアップロード',
    analyze_btn: 'AIで解析する',
    settings: '設定',
    model_label: '使用モデル',
    feedback_title: '解析結果',
    score_label: 'スコア',
    overall_section: '総評',
    pronunciation_section: '発音のアドバイス',
    intonation_section: 'イントネーション',
    suggestions_section: '具体的な改善点',
    transcription_label: '聞き取った内容',
    waiting_message: '解析中...',
    select_audio_msg: '音声を選択または録音してください',
    reanalyze: '再評価',
    translate_btn: '翻訳',
    translating: '翻訳中...',
    reset: 'やり直す'
  },
  en: {
    title: 'Koe-Master',
    subtitle: 'AI Japanese Pronunciation Coach',
    mode_text: 'Text Mode',
    mode_free: 'Free Talk',
    level_beginner: 'Beginner',
    level_intermediate: 'Intermediate',
    level_advanced: 'Advanced',
    placeholder_text: 'Enter the text you want to practice...',
    start_recording: 'Start Recording',
    stop_recording: 'Stop Recording',
    upload_file: 'Upload Audio',
    analyze_btn: 'Analyze with AI',
    settings: 'Settings',
    model_label: 'Model',
    feedback_title: 'Analysis Result',
    score_label: 'Score',
    overall_section: 'Overall',
    pronunciation_section: 'Pronunciation Advice',
    intonation_section: 'Intonation',
    suggestions_section: 'Specific Improvements',
    transcription_label: 'Transcription',
    waiting_message: 'Analyzing...',
    select_audio_msg: 'Please select or record audio',
    reanalyze: 'Re-analyze',
    translate_btn: 'Translate',
    translating: 'Translating...',
    reset: 'Reset'
  },
  zh: {
    title: 'Koe-Master',
    subtitle: 'AI日语发音教练',
    mode_text: '文本练习',
    mode_free: '自由交谈',
    level_beginner: '初级',
    level_intermediate: '中级',
    level_advanced: '高级',
    placeholder_text: '输入你想练习的日语...',
    start_recording: '开始录音',
    stop_recording: '停止录音',
    upload_file: '上传音频',
    analyze_btn: '使用AI分析',
    settings: '设置',
    model_label: '使用模型',
    feedback_title: '分析结果',
    score_label: '评分',
    overall_section: '综合评价',
    pronunciation_section: '发音建议',
    intonation_section: '语调',
    suggestions_section: '具体改进点',
    transcription_label: '听取内容',
    waiting_message: '正在分析...',
    select_audio_msg: '请选择或录制音频',
    reanalyze: '重新分析',
    translate_btn: '翻译',
    translating: '翻译中...',
    reset: '重置'
  },
  ko: {
    title: 'Koe-Master',
    subtitle: 'AI 일본어 발음 코치',
    mode_text: '텍스트 연습',
    mode_free: '자유 발화',
    level_beginner: '초급',
    level_intermediate: '중급',
    level_advanced: '고급',
    placeholder_text: '연습하고 싶은 일본어를 입력하세요...',
    start_recording: '녹음 시작',
    stop_recording: '녹음 중지',
    upload_file: '음성 파일 업로드',
    analyze_btn: 'AI로 분석하기',
    settings: '설정',
    model_label: '사용 모델',
    feedback_title: '분석 결과',
    score_label: '점수',
    overall_section: '총평',
    pronunciation_section: '발음 조언',
    intonation_section: '억양',
    suggestions_section: '구체적인 개선점',
    transcription_label: '인식된 내용',
    waiting_message: '분석 중...',
    select_audio_msg: '음성을 선택하거나 녹음해 주세요',
    reanalyze: '재분석',
    translate_btn: '번역',
    translating: '번역 중...',
    reset: '초기화'
  }
};
